version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password
      POSTGRES_DB: db_monolito
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - devfest

  monolito:
    build: .
    container_name: monolito
    depends_on:
      - postgres
    environment:
      PG_HOST: postgres
      PG_DATABASE: db_monolito
      PG_USER: my_user
      PG_PASSWORD: my_password
      PG_PORT: 5432
      PORT: 3001
    ports:
      - "3001:3001"
    networks:
      - devfest

volumes:
  postgres-data:

networks:
  devfest:
